# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle (jar)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Make a distrib zip
        uses: gradle/gradle-build-action@v2
        with:
          arguments: overlayDistZip